#!/bin/bash
clear
echo -e ""
echo -e "\e[94m.-------------------------------------------------."
echo -e "\e[94m|               Autoscript By Royn                |"
echo -e "\e[94m'-------------------------------------------------'"
echo -e "\e[0m"
echo -e "\e[94m==================================================="
echo -e "\e[94m# Support Debian 9 & Debian 10 64 bit             #"
echo -e "\e[94m# Support Ubuntu 18.04 & Ubuntu 20.04 64 bit      #"
echo -e "\e[94m# For VPS with KVM and VMWare virtualization      #"
echo -e "\e[94m#                                                 #"
echo -e "\e[94m#-------------------------------------------------#"
echo -e "\e[94m#       THANKS FOR PURCHASE THIS AUTOSCRIPTS      #"
echo -e "\e[94m#-------------------------------------------------#"
echo -e "\e[94m#                                                 #"
echo -e "\e[94m# Telegram : t.me/royn628                         #"
echo -e "\e[94m#                                                 #"
echo -e "\e[94m#-------------------------------------------------#"
echo -e "\e[94m#            © Copyright 2021 By Royn             #"
echo -e "\e[94m==================================================="
echo -e "\e[0m"